/******************************************************************************/
#include <Engine/Headers/EsenthelEngine.h>
/******************************************************************************/
// THIS IS AN AUTOMATICALLY GENERATED FILE
// THIS FILE WAS GENERATED BY ESENTHEL EDITOR, ACCORDING TO PROJECT SETTINGS
/******************************************************************************/
// CONSTANTS
/******************************************************************************/
const bool EE_MOBILE= // if compiling for mobile platform
#ifdef MOBILE
   true
#else
   false
#endif
;
const bool EE_WEB= // if compiling for web platform
#ifdef WEB
   true
#else
   false
#endif
;
const Bool EE_PUBLISH       =false; // this is set to true when compiling for publishing
const Bool EE_ENGINE_EMBED = (false && !EE_MOBILE); // this is set to true when "Embed Engine Data" was enabled in application settings, this is always disabled for Mobile builds
CChar *   EE_PHYSX_DLL_PATH=(                            (EE_WEB || EE_PUBLISH) ? L"Bin"             : L"Engine");
CChar *   EE_ENGINE_PATH   =(EE_MOBILE ? L"Engine.pak"  : (EE_WEB || EE_PUBLISH) ? L"Bin/Engine.pak"  : L"Engine/Engine.pak");
CChar *   EE_PROJECT_PATH  =(EE_MOBILE ? L"Project.pak" : (EE_WEB || EE_PUBLISH) ? L"Bin/Project.pak" : L"2gernl2x1m66615wx8#sh8_n/Game");
CChar *   EE_PROJECT_NAME  =L"Pandemic";
CChar *   EE_APP_NAME      =L"Pandemic";
const UID  EE_GUI_SKIN      =UID(0, 0, 0, 0);
Secure*C   EE_PROJECT_SECURE=nullptr;
void EE_INIT_OBJ_TYPE() // this function will setup Game.ObjType enum used for game object types
{
}
/******************************************************************************/
// FUNCTIONS
/******************************************************************************/
void EE_INIT(bool load_engine_data, bool load_project_data)
{
   App.name(EE_APP_NAME); // set application name
   EE_INIT_OBJ_TYPE(); // initialize game object type enum
   if (load_engine_data) {
	   if (!EE_ENGINE_EMBED) {
		   Paks.add(EE_ENGINE_PATH); // load engine data
	   }
   }

   if(load_project_data) {
	   if (EE_MOBILE || EE_WEB || EE_PUBLISH) {
		   Paks.add(EE_PROJECT_PATH, EE_PROJECT_SECURE); 
	   } else {
		   DataPath(EE_PROJECT_PATH);
	   }
   } // load project data
}
/******************************************************************************/
// ENUMS
/******************************************************************************/

/******************************************************************************/
